<?php
//ELMS: Profiler Builder
//Development Sponsored by The Pennsylvania State University
//ELMS is Copyright (C) 2008-2011  The Pennsylvania State University
//
//Bryan Ollendyke
//bto108@psu.edu
//
//Keith D. Bailey
//kdb163@psu.edu
//
//12 Borland
//University Park,  PA 16802
/**
 * Implementation of hook_perm().
 */
function profiler_builder_perm() {
  return array('administer profiler builder');
}

/**
 * Implementation of hook_menu().
 */
function profiler_builder_menu() {
  $items = array();
  $items['admin/settings/profiler_builder'] = array(
    'title' => 'Profiler Builder',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_profiler_builder_settings'),
    'description' => 'Build distribution files from current settings',
    'access arguments' => array('administer profiler builder'),
  );
  return $items;
}
/**
 * Implementation of hook_settings().
 */
function _profiler_builder_settings() {
  $form = array();
  //call helper function to populate the three fields
  _profiler_builder_info_file($info, $vars, $drush);
  //info file
  $form['info_file'] = array(
    '#weight' => '0',
    '#description' => t('This is what the .info file would look like if you were to make a distribution off of this site as it exists currently.'),
    '#collapsed' => '1',
    '#type' => 'fieldset',
    '#collapsible' => '1',
    '#title' => t('.info file'),
  );
  $form['info_file']['info_file_contents'] = array(
    '#description' => t('Copy this into your .info file for the distribution you are making'),
    '#weight' => '0',
    '#type' => 'textarea',
    '#title' => t('File contents'),
    '#value' => $info,
  );
  $form['info_file']['vars'] = array(
    '#description' => t('Cheatsheet for all variables'),
    '#weight' => '1',
    '#type' => 'textarea',
    '#title' => t('Variables'),
    '#value' => $vars,
  );
  //drush make
  $form['drush_file'] = array(
    '#weight' => '0',
    '#description' => t('This is what the .make file would look like if you were to make a distribution off of this site as it exists currently.'),
    '#collapsed' => '1',
    '#type' => 'fieldset',
    '#collapsible' => '1',
    '#title' => t('.make file'),
  );
  $form['drush_file']['drush_file_contents'] = array(
    '#description' => t('Copy this into your .make file for the distribution you are making'),
    '#weight' => '1',
    '#type' => 'textarea',
    '#title' => t('File contents'),
    '#value' => $drush,
  );
  return $form;
}

//helper function to build out the file pieces
function _profiler_builder_info_file(&$info, &$vars, &$drush) {
  //build the array we need
  $result = db_query("SELECT * FROM {system} WHERE status=1 AND type='module'");
  while ($val = db_fetch_array($result)) {
    $system[$val['name']] = unserialize($val['info']);
  }
  //convert data
  foreach ($system as $module => $info) {
    //account for the other package in module listing
    if (!isset($info['package'])) {
      $info['package'] = 'Other';
    }
    $data[$info['package']][$module] = $info['version'];
  }
  //info file of required modules
  $info = '';
  foreach ($data as $package => $projects) {
    $info .= '; '. $package ."\n";
    foreach ($projects as $project => $version) {
      $info .= 'dependencies[] = "'. $project .'"'."\n";
    }
  }
  //variables
  $vars = "; Variables\n\n";
  //array of values we know to ignore automatically
  $ignore_list = _profiler_builder_ignore_list();
  $result = db_query("SELECT name FROM {variable} WHERE name NOT IN (". db_placeholders($ignore_list, 'text') .")", $ignore_list);
  //really annoying function but we need to go into SUPER deeply nested values so that they can be fed into profiler correctly
  //TODO: Probably a better way of doing this but this will work for now
  while ($value = db_fetch_array($result)) {
    $val = variable_get($value['name'], '');
    if ($val != '') {
      if (is_array($val)) {
        foreach ($val as $key => $ary_val) {
          if (is_array($ary_val)) {
            foreach ($ary_val as $key2 => $ary_val2) {
              if (is_array($ary_val2)) {
                foreach ($ary_val2 as $key3 => $ary_val3) {
                  if (is_array($ary_val3)) {
                    foreach ($ary_val3 as $key4 => $ary_val4) {
                      $vars .= 'variables['. $value['name'] .']['. $key .']['. $key2 .']['. $key3 .']['. $key4 .'] = "'. $ary_val4 .'"'."\n";
                    }
                  }
                  else {
                    $vars .= 'variables['. $value['name'] .']['. $key .']['. $key2 .']['. $key3 .'] = "'. $ary_val3 .'"'."\n";
                  }
                }
              }
              else {
                $vars .= 'variables['. $value['name'] .']['. $key .']['. $key2 .'] = "'. $ary_val2 .'"'."\n";
              }
            }
          }
          else {
            $vars .= 'variables['. $value['name'] .']['. $key .'] = "'. $ary_val .'"'."\n";
          }
        }
      }
      else {
        $vars .= 'variables['. $value['name'] .'] = "'. $val .'"'."\n";
      }
    }
  }
  //drush
  $drush = '';
  foreach ($data as $package => $projects) {
    foreach ($projects as $project => $version) {
      $drush .= 'projects['. $project .'] = '. str_replace('6.x-', '', $version) ."\n";
    }
  }
  return 1;
}

//helper function to gather ignored values
function _profiler_builder_ignore_list() {
  return array(
    'features_codecache',
    'views_block_hashes',
    'drupal_private_key',
    'cache_content_flush_cache_block',
    'cache_content_flush_cache_page',
    'cache_flush_cache_update',
    //TODO: abstract into a hook as these are psu specific
    'webaccess_cookie',
    'webaccess_domain',
    'webaccess_init_enable',
    'webaccess_logout_url',
  );
}